### ISSUE TITLE
README.md "How to use" section is not functional code, doesn't work

### ISSUE THREAD

**Issue by gittes** [OnFreund/PyKodi#2]
I presume it's rough pseudo example code, but I was hoping for a quick functional example please.

I guess I'll learn aysnc/await syntax in the meantime.

Thank you for writing this!

Using python 3.8.5.

**Comment by OnFreund** [comment]
Hey @gittes if you're running within an async context (e.g. [aioconsole](https://pypi.org/project/aioconsole/)) this is mostly cut and paste, and passing the relevant values for your environment to `get_kodi_connection()`.

It's an async library, so yes, understanding async/await is imperative to using it optimally.
